### ISSUE TITLE
grafana-agent install fails on intel hardware

### ISSUE THREAD

**Issue by attachmentgenie** [grafana/homebrew-grafana#24]
```
~ ❯ brew install grafana/grafana/grafana-agent
==> Downloading https://ghcr.io/v2/homebrew/core/grafana-agent/manifests/0.23.0
Already downloaded: /Users/attachmentgenie/Library/Caches/Homebrew/downloads/a96d5dd86527042d895d6b71f65ac76fef4eabbb0ed318c66b7d30f12e086cd5--grafana-agent-0.23.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/grafana-agent/manifests/0.23.0
######################################################################## 100.0%
Error: Couldn't find manifest matching bottle checksum.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:413:in `github_packages_manifest_resource_tab'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:366:in `fetch_tab'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2392:in `fetch_bottle_tab'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1182:in `fetch'
/usr/local/Homebrew/Library/Homebrew/install.rb:305:in `block in install_formulae'
/usr/local/Homebrew/Library/Homebrew/install.rb:278:in `map'
/usr/local/Homebrew/Library/Homebrew/install.rb:278:in `install_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:218:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

**Comment by rfratto** [comment]
Thanks for reporting! cc @rlankfo

**Comment by rlankfo** [comment]
@attachmentgenie looks like we need to update our bottle checksums in this tap. In the meantime, you should be able to install `grafana-agent 0.23.0` from homebrew core:
```
brew install grafana-agent
```

**Comment by rlankfo** [comment]
@attachmentgenie I've updated the bottles so this should be resolved for installing from the Grafana vendor tap as well:

```
➜  homebrew-grafana git:(rlankfo/grafana-agent-bottles) brew install grafana/grafana/grafana-agent
==> Auto-updated Homebrew!
Updated 1 tap (grafana/grafana).
==> Updated Formulae
Updated 1 formula.

==> Downloading https://ghcr.io/v2/homebrew/core/grafana-agent/manifests/0.23.0
Already downloaded: /Users/robertlankford/Library/Caches/Homebrew/downloads/a96d5dd86527042d895d6b71f65ac76fef4eabbb0ed318c66b7d30f12e086cd5--grafana-agent-0.23.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/grafana-agent/blobs/sha256:bab099008ea51ea316dd70c4d9673ac7eab6149dd3b9c62ab198b8ca7df15880
Already downloaded: /Users/robertlankford/Library/Caches/Homebrew/downloads/845cae705a0f555c91228a2514793f5c3e5824871651a839787b0d1726dbee1d--grafana-agent--0.23.0.arm64_monterey.bottle.tar.gz
==> Installing grafana-agent from grafana/grafana
==> Pouring grafana-agent--0.23.0.arm64_monterey.bottle.tar.gz
==> Caveats
The agent uses a configuration file that you must customize before running:
  /opt/homebrew/etc/grafana-agent/config.yml

To restart grafana/grafana/grafana-agent after an upgrade:
  brew services restart grafana/grafana/grafana-agent
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/grafana-agent/bin/grafana-agent -config.file /opt/homebrew/etc/grafana-agent/config.yml
==> Summary
🍺  /opt/homebrew/Cellar/grafana-agent/0.23.0: 9 files, 260.2MB
==> Running `brew cleanup grafana-agent`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```
